navigation_filter_node:
    ros__parameters:
        Rate: 10
        Gains: [1.0, 1.0, 0.2, 0.2]
        ThrusterMapping:
            cX: [0.0, 0.0, 45.47]
            cN: [520.0, 0.0, 600.0]
            Inertia: [400.0, 400.0, 50.0]
        CovarianceAngle:
            diagonal: [0.0, 0.0, 0.0]
        CovarianceMeasureAngle:
            diagonal: [0.0, 0.0, 0.0]
        CovarianceModel:
            diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        CovarianceMeasure:
            diagonal: [0.0, 0.0, 0.0, 0.0]

