rate: 100

filterMode: 1 # 0: Luenberger Observer, 1: EKF

luenbergerObserver:
{
    gain: [5.0, 5.0, 0.2, 0.2];

    yawRateFilterGains: [0.9, 0.1];
};

extendedKalmanFilter:
{
    ulisseModel:
    {
        lambdaPos: 13.0;
        lambdaNeg: 9.1;
        motorsDistance: 0.7;
        cX: [0.0, 0.0, 33.97];
        cN: [270.0, 0.0, 236.0];
        b1Pos: 0.000303;
        b2Pos: 0.013;
        b1Neg: 0.000143;
        b2Neg: 0.021;
        inertia: [400.0, 400.0, 400.0];
    };

    state:
    {
        dim: 17;

        initialization: [44.4, 8.94, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

        initializationCovariance: [100.0, 100.0, 0.0001, 100.0, 100.0, 100.0, 1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1.0, 1.0, 1.0, 1.0, 1.0];

        modelCovariance: [1e-07, 1e-07, 1e-07, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08];
    };

    measures:
    {
        gps:
        {
            enable: true;
            covariance: [0.49, 0.49, 0.0];
        }

        compass:
        {
            enable: false;
            covariance: [0.0003046247, 0.0003046247, 0.000121847];
        }

        accelerometer:
        {
            enable: true;
            covariance: [0.009617, 0.009617, 0.009617];
        }

        magnetometer:
        {
            enable: true;
            covariance: [0.000121847];
        }

        gyro:
        {
            enable: true;
            covariance: [0.00030446, 0.00030446, 0.00030461];
        }
    };

};





	
