rate: 100

#centroidLocation = [44.392, 8.945];    #genova coordinates
#centroidLocation = [44.0939844, 9.8627768]; #depalo
centroidLocation = [44.0956, 9.8631]; #laspezia coordinates

filterMode: 2 # 0: Ground Truth, 1: Luenberger Observer, 2: EKF

thrusterFIFOdelayLength: 20

luenbergerObserver:
{
    gain: [5.0, 5.0, 0.2, 0.2];

    yawRateFilterGains: [0.9, 0.1];
};

extendedKalmanFilter:
{
    #0 = simplified CoM frame
    #1 = complete body frame
    version: 1;

    state:
    {
        dim: 19;

        initialization: [44.0956, 9.8631, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

        initializationCovariance: [100.0, 100.0, 0.0, 1e-8, 1e-8, 1.0, 1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-2, 1e-2, 1.0, 1.0, 1.0, 0.01, 0.01];

        modelCovariance: [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,  1e-6, 1e-6, 1e-8,    1e-05, 1e-05, 1e-5,    5e-8, 5e-8,   1e-10, 1e-10, 1e-10, 5e-3, 5e-3];
    };

    measures:
    {
        gps:
        {
            enable: true;
            #covariance: [0.49, 0.49];
            covariance: [0.1, 0.1];
            bodyF_gps_position: [-0.750, 0.0, -1.635];
        }

        compass:
        {
            enable: false;
            covariance: [0.0003046247, 0.0003046247, 0.000121847];
        }

        accelerometer:
        {
            enable: true;
            #covariance: [0.009617, 0.009617, 0.009617];
            covariance: [0.09617, 0.09617, 0.09617];
            
        }

        magnetometer:
        {
            enable: true;
            #covariance: [0.000121847];
            #covariance: [0.00121847];
             covariance: [0.0005];
        }

        gyro:
        {
            enable: true;
            covariance: [0.00030446, 0.00030446, 0.00030461];
           
        }

        z_meter:
        {
            enable: true;
            covariance: [0.0];
        };
        
        rpm:
        {
            enable: true;
            covariance: [0.1];
        };
    };

};





	
