rate: 100

filterMode: 2 # 0: Ground Truth, 1: Luenberger Observer, 2: EKF

luenbergerObserver:
{
    gain: [5.0, 5.0, 0.2, 0.2];

    yawRateFilterGains: [0.9, 0.1];
};

extendedKalmanFilter:
{
    ulisseModel:
    {
        lambdaPos: 13.0;
        lambdaNeg: 9.1;
        motorsDistance: 0.6925;
        cX: [0.0, 0.0, 34.22];
        cY: [0.0, 6.834, 68.44];
        cN: [268.8, 0.0, 270.1];
        cNneg: [-101.7, 0.0, 1103.0];
        b1Pos: 3.03E-4;
        b2Pos: 1.4E-2;
        b1Neg: 1.37E-4;
        b2Neg: 1.9E-2;
        inertia: [400.0, 400.0, 400.0];
        hullWidth: 0.4;
    };


    state:
    {
        dim: 17;
          #37.94, -8.87
        initialization: [44.4, 8.94 , 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

        initializationCovariance: [100.0, 100.0, 0.0, 0.001, 0.001, 0.001, 1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  0.001, 0.001, 1.0, 1.0, 1.0];

        modelCovariance: [1e-06, 1e-06, 1e-05, 1e-08,1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-04, 1e-04, 1e-06, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08];
    };

    measures:
    {
        gps:
        {
            enable: true;
            covariance: [0.49, 0.49];
            bodyF_gps_position: [-0.49, 0.0, -1.0];
        }

        compass:
        {
            enable: false;
            covariance: [0.0003046247, 0.0003046247, 0.000121847];
        }

        accelerometer:
        {
            enable: true;
            covariance: [0.009617, 0.009617, 0.009617];
        }

        magnetometer:
        {
            enable: true;
            covariance: [0.000121847];
        }

        gyro:
        {
            enable: true;
            covariance: [0.00030446, 0.00030446, 0.00030461];
        }

        z_meter:
        {
            enable: true;
            covariance: [0.0];
        };
    };

};





	
