rate: 100

filterMode: 2 # 0: Ground Truth, 1: Luenberger Observer, 2: EKF

thrusterFIFOdelayLength: 20

luenbergerObserver:
{
    gain: [5.0, 5.0, 0.2, 0.2];

    yawRateFilterGains: [0.9, 0.1];
};

extendedKalmanFilter:
{
    #0 = simplified CoM frame
    #1 = complete body frame
    version: 0;

    ulisseModel:
    {
        lambdaPos: 13.8;
        lambdaNeg: 10.1;
        motorsTransversalDistance: 0.6925;
        motorsLongitudinalDistance: 1.5;
        #cX: [0.0, 0.0, 40.29];
        #cY: [0.0, 0.0, 80.58];
        #cN: [326.69, 0.0, 272.58];
        #cNneg: [-169.75, 0.0, 841.03];
        #b1Pos: 3.03E-4;
        #b2Pos: 0.0;
        #b1Neg: 1.46E-4;
        #b2Neg: 2.5E-2;
        
        #cX: [0.0, 0.0, 58.0];
        #cY: [0.0, 0.0, 120.0];
        #cN: [470.0, 0.0, 392.5];
        #cNneg: [-244.5, 0.0, 1211.0];
        #b1Pos: 3.03E-4;
        #b2Pos: 0.0;
        #b1Neg: 1.46E-4;
        #b2Neg: 3.0E-2;
        
        cX: [0.0, 0.0, 65.0];
        cY: [0.0, 0.0, 300.0];
        cN: [477.0, 0.0, 0.0];
        cNneg: [0.0, 0.0, 1377.0];
        b1Pos: 3.03E-4;
        b2Pos: 0.0;
        b1Neg: 1.37E-4;
        b2Neg: 0.0;
        kPos: 0.069;
        kNeg: 0.31;
        rpmDynState: 0.9718;
        rpmDynPosPerc: 0.3887;
        rpmDynNegPerc: 0.2845;
        
        inertia: [400.0, 400.0, 300.0];
        hullWidth: 0.4;
    };


    state:
    {
      	dim: 19;

        initialization: [44.393, 8.945, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0];

        initializationCovariance: [100.0, 100.0, 0.0, 1e-8, 1e-8, 1.0, 1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-08,  1e-2, 1e-2, 1.0, 1.0, 1.0, 0.01, 0.01];

        #modelCovariance: [1e-6, 1e-6, 1e-6,  1e-08,1e-08, 1e-08,     1e-6, 1e-6, 1e-06,    1e-04, 1e-04, 1e-05,    1e-7, 1e-7,   1e-10, 1e-10, 1e-10, 1e-2, 1e-2];
        #modelCovariance: [0.0, 0.0, 0.0,  0.0, 0.0, 0.0,     1e-7, 1e-7, 1e-06,    1e-04, 1e-04, 5e-06,    1e-7, 1e-7,   1e-10, 1e-10, 1e-10, 5e-3, 5e-3];
        modelCovariance: [1e-4, 1e-4, 1e-4,  0.0, 0.0, 0.0,     1e-6, 1e-6, 1e-8,    1e-05, 1e-05, 1e-6,    1e-7, 1e-7,   1e-10, 1e-10, 1e-10, 5e-3, 5e-3];
    };

    measures:
    {
        gps:
        {
            enable: true;
            #covariance: [0.49, 0.49];
            covariance: [0.1, 0.1];
            bodyF_gps_position: [-0.750, 0.0, -1.635];
        }

        compass:
        {
            enable: false;
            covariance: [0.0003046247, 0.0003046247, 0.000121847];
        }

        accelerometer:
        {
            enable: true;
            #covariance: [0.009617, 0.009617, 0.009617];
            covariance: [0.09617, 0.09617, 0.09617];
            
        }

        magnetometer:
        {
            enable: true;
            covariance: [0.000121847];
            #covariance: [0.00121847];
        }

        gyro:
        {
            enable: true;
            covariance: [0.00030446, 0.00030446, 0.00030461];
           
        }

        z_meter:
        {
            enable: true;
            covariance: [0.0];
        };
        
        rpm:
        {
            enable: true;
            covariance: [0.1];
        };
    };

};





	
