dcl_ulisse:
{
    controlLoopPeriod: 100;         # ms
    ctrlMode: 1;                  # 0=ThrusterMapping, 1=DynamicModel, 2=ComputedTorque
    enableThrusters: true;
    thrusterPercLimit: 70.0;         # percent

    # input saturation limits
    surgeMin: -5.0;
    surgeMax: 5.0;    # Be careful to make the PID Surge saturation smaller than this values !
    yawRateMin: -0.5;
    yawRateMax: 0.5;  # Be careful to make the PID Heading saturation smaller than this values !

    ulisseModel:
    {
        lambdaPos: 13.0;
        lambdaNeg: 9.1;
        motorsDistance: 0.6925;
        cX: [0.0, 0.0, 34.22];
        cN: [268.8, 0.0, 270.1];
        cNneg: [-101.7, 0.0, 1103.0];
        b1Pos: 3.03E-4;
        b2Pos: 1.4E-2;
        b1Neg: 1.37E-4;
        b2Neg: 1.9E-2;
        inertia: [400.0, 400.0, 400.0];
        hullWidth: 0.4;
    };

	
    thrusterMapping:
    {
        pidSurge:
        {
            kp: 8.0;
            ki: 0.4;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat: 2.5;
        };
    };

    classicPidControl:
    {
        pidSurge:
        {
            kp: 260.0
            ki: 25.0;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat:400.0;
        };

        pidYawRate:
        {
            kp: 1000.0;
            ki: 400.0;
            kd: 0.0;
            kff: 0.0;
            n: 10.0;
            tr: 0.5;
            sat: 560.0;
         };
    };

    computedTorqueControl:
    {
        pidSurge:
        {
            kp: 200.0
            ki: 0.0;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat:400.0;
        };

        pidYawRate:
        {
            kp: 450.0;
            ki: 0.0;
            kd: 0.0;
            kff: 0.0;
            n: 10.0;
            tr: 0.5;
            sat: 560.0;
        };
    };
};
