dcl_ulisse:
{
    controlLoopPeriod: 100;         # ms
    ctrlMode: 2;                    # 0=ThrusterMapping, 1=classicPidControl, 2=ComputedTorque
    enableThrusters: true;
    thrusterPercLimit: 100.0;        # percent

    # input saturation limits
    surgeMin: -5.0;
    surgeMax: 5.0;    # Be careful to make the PID Surge saturation smaller than this values !
    yawRateMin: -0.5;
    yawRateMax: 0.5;  # Be careful to make the PID Heading saturation smaller than this values !

	
    thrusterMapping:
    {
        pidSurge:
        {
            kp: 8.0;
            ki: 0.4;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat: 2.5;
        };
    };

    classicPidControl:
    {
        pidSurge:
        {
            kp: 260.0
            ki: 25.0;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat:400.0;
        };

        pidYawRate:
        {
            kp: 500.0;#1000.0;
            ki: 200.0;#400.0;
            kd: 0.0;
            kff: 0.0;
            n: 10.0;
            tr: 0.5;
            sat: 560.0;
         };
    };

    computedTorqueControl:
    {
        pidSurge:
        {
            kp: 200.0
            ki: 0.0;
            kd: 0.0;
            kff: 0.6;
            n: 10.0;
            tr: 0.5;
            sat:400.0;
        };

        pidYawRate:
        {
            kp: 600.0;#450.0;
            ki: 0.0;
            kd: 0.0;
            kff: 0.0;
            n: 10.0;
            tr: 0.5;
            sat: 560.0;
        };
    };
};
