low_level_control_params:
{
        ControlLoopPeriod: 100;         # ms

        ControlMode: 2;                  # 0=ThrusterMapping, 1=DynamicModel, 2=SlidingMode

        EnableThrusters: true;
        SpeedLimiter: 2.5;             # m/s [Be careful to make the mapping saturation bigger than this values] (to avoid double saturation)
        JogLimiter: 0.3;               # rad/s
        ForceLimiter: 400.0;
        TorqueLimiter: 560.0;
        ThrusterPercLimit: 70.0;         # percent

        ThrusterMapping:
	{
            # input saturation limits
            SurgeMin: -5.0;
            SurgeMax: 5.0;    # Be careful to make the PID Surge saturation smaller than this values !
            YawRateMin: -0.5;
            YawRateMax: 0.5;  # Be careful to make the PID Heading saturation smaller than this values !
            # mapping parameters
            lambda_pos: 13.0;
            lambda_neg: 9.1;
            motors_distance: 0.6925;
            cX: [0.0, 0.0, 45.47];
            cN: [520.0, 0.0, 600.0];
            b1_pos: 0.000303;
            b2_pos: 0.034;
            b1_neg: 0.00014;
            b2_neg: 0.055;
            Inertia: [400.0, 400.0, 50.0];
            PIDSurge:
	    {
                Kp: 0.4;
                Ki: 0.4;
                Kd: 0.0;
                Kff: 0.6;
                N: 10.0;
                Tr: 0.5;
            };
	};

        DynamicControl:
	{
            PIDSurge:
	   {
                Kp: 0.4;
                Ki: 0.4;
                Kd: 0.0;
                Kff: 0.6;
                N: 10.0;
                Tr: 0.5;
	    };
            PIDYawRate:
	    {
                Kp: 0.75;
                Ki: 0.00;
                Kd: 0.0;
                Kff: 0.0;
                N: 10.0;
                Tr: 0.5;
	     };
	};

        sliding_surface:
	{
            gain_1: 1.0;
            gain_2: 0.5;
	};

        sliding_control_parameter:
	{
            surge: 0.2;
            heading: 5.5;
	};

        filter_parameter:
        {
            gains: [0.9, 0.1];
	};

};

