controller_node:
    ros__parameters:
        ControlLoopPeriod: 100          # ms

        PosAcceptanceRadius: 5.0

        SpeedLimiter: 2.5               # m/s [Be careful to make the mapping saturation bigger than this values] (to avoid double saturation)
        JogLimiter: 2.5                 # rad/s

        #DistanceThreshold: 5.0          # m
        #MaximumTargetDistance: 50000.0  # m

        Hold:
            enableCurrentCompensation: true
            Hysteresis: 2.0
            DefaultRadius: 3.0
            # above CurrentMax the desired heading will be set equal to the
            # estimated current direction
            # below CurrentMin the desired heading is the actual one
            CurrentMin: 0.0
            CurrentMax: 0.1

        GotoHoldAfterMove: true

        #UsePosVelObserver: false

        SlowDownOnTurns:
            enable: true
            HeadingErrorMin: 0.1 # 10.0 degrllc
            HeadingErrorMax: 0.5 # 25.0 degress
            AlphaMin: 0.1
            AlphaMax: 1.0

        AvoidRotationCloseToTarget:
            enable: true
            SpeedMin: 0.1
            SpeedMax: 0.25
            BetaMin: 0.01
            BetaMax: 1.0

        PIDPosition:
            Kp: 0.1
            Ki: 0.0
            Kd: 0.0
            Kff: 0.0
            N: 10.0
            Tr: 0.5

        PIDSpeed:
            Kp: 0.4
            Ki: 0.4
            Kd: 0.0
            Kff: 0.6
            N: 10.0
            Tr: 0.5

        PIDHeading:
            Kp: 0.75
            Ki: 0.0
            Kd: 1.5
            Kff: 0.0
            N: 10.0
            Tr: 0.5
