controlLoopPeriod = 100.0;         # ms
posAcceptanceRadius = 5.0;       # m
goToHoldAfterMove = true;
saturationMax = [10.0, 10.0, 0.3, 1.0, 10.0, 10.0];
saturationMin = [-10.0, -10.0, -0.3, -10.0, -10.0, -10.0];

tasks = ( {  name = "ASV_Linear_Velocity";
             gain = 1.0;
             enable = true;
             saturation = 10.0; },

          {  name = "ASV_Safety_Boundaries";
             gain = 1.0;
             enable = true;
             saturation = 10.0;
             decreasingBellShaped = { xmin = [3.0, 0.0, 0.0];
                                     xmax = [8.0, 0.0, 0.0]; }; },

          {  name = "ASV_Angular_Position";
             gain = 0.3;
             enable = true;
             saturation = 10.0; },

          {  name = "ASV_Absolute_Axis_Alignment";
             gain = 0.3;
             enable = true;
             saturation = 10.0; },

          {  name = "ASV_Absolute_Axis_Alignment_Safety";
             gain = 0.3;
             enable = true;
             saturation = 10.0; },

          {  name = "ASV_Cartesian_Distance";
             gain = 0.1;
             enable = true;
             saturation = 10.0; } );



priorityLevels = ( {  name = "PL_Safety";
                      tasks = ["ASV_Safety_Boundaries","ASV_Absolute_Axis_Alignment_Safety"];
                      lambda = 0.0001;
                      threshold = 0.01; },

                   {  name = "PL_Go_To";
                      tasks = ["ASV_Angular_Position","ASV_Cartesian_Distance"];
                      lambda = 0.0001;
                      threshold = 0.01; },

                   {  name = "PL_Speed_Heading";
                      tasks = ["ASV_Linear_Velocity","ASV_Absolute_Axis_Alignment"];
                      lambda = 0.0001;
                      threshold = 0.01; } );

actions = ( {  name = "Go_To";
               levels = ["PL_Safety","PL_Go_To"]; },

            {  name = "Hold";
               levels = ["PL_Safety","PL_Speed_Heading"]; },

            {  name = "Idle";
               levels = ["PL_Safety"]; },

            {  name = "Path_Following";
               levels = ["PL_Safety","PL_Go_To"]; },

            {  name = "Speed_Heading";
               levels = ["PL_Safety","PL_Speed_Heading"]; } );

states = ( {  name = "State_Halt"
              minHeadingError = "M_PI/64";
              maxHeadingError = "M_P1/16"; },

           {  name = "State_Hold";
              minHeadingError = "M_PI/64";
              maxHeadingError = "M_P1/16"; },

           {  name = "State_Go_To";
              minHeadingError = "M_PI/64";
              maxHeadingError = "M_P1/16"; },

           {  name = "State_Speed_Heading";
              minHeadingError = "M_PI/64";
              maxHeadingError = "M_P1/16"; },

           {  name = "State_Path_Following";
              minHeadingError = "M_PI/64";
              maxHeadingError = "M_P1/16";
              maximumLookupAbscissa = 0.5;
              delta = 2.0;
              useLineOfSight = false;
              tolleranceStartingPoint = 2.0;
              tolleranceEndingPoint = 2.0;
              tolleranceStartingAngle = 0.05; } );
