priorityLevel:
{
       saturationMax = [0.0, 0.0, 2.0, 2.5, 0.0, 0.0];

       saturationMin = [0.0, 0.0, -2.0, 0.0, 0.0, 0.0];
	
        ASV_hold_position_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_linear_position_go_to_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_attitude_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };
	
        ASV_direction_alignment_PL:
	{	    
	
		regularizationParameter:
		{
                        lambda=0.0001;
                        threshold=0.01;
		}; 
		
	};

        ASV_control_velocity_linear_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_velocity_angular_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_position_angular_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_distance_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_make_curve_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_safety_boundaries_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

};
