priorityLevel:
{
       saturationMax = [10.0, 10.0, 0.3, 1.0, 10.0, 10.0];

       saturationMin = [-10.0, -10.0, -0.3, -10.0, -10.0, -10.0];
	
        ASV_hold_position_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_velocity_linear_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_velocity_angular_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_position_angular_PL:
        {

                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_control_distance_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_make_curve_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

        ASV_safety_boundaries_PL:
        {
                regularizationParameter:
                {
                        lambda=0.0001;
                        threshold=0.01;
                };

        };

};
