task:
{
        ASV_control_velocity_linear:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
        };

        ASV_control_velocity_angular:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
        };

        ASV_hold_position:
        {
                gain = 0.3;
                taskEnable = true;
                saturation = 10.0;
                controlReference = [0.0, 0.0, 0.0];
        };
	
        ASV_safety_boundaries:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
                tollerance = [0.05];
                AlphaMin = 0.2;
                DesiredSpeed = 2.5;
                BoundaryMinimumDistance = 8.0;
                BoundaryMaximumDistance = 3.0;
        };

        PathFollowing:
        {
            MaximumLookupAbscissa = 0.5;
            Delta = 5.0;
            UseLineOfSight = true;
            TolleranceStartingPoint = 2.0;
            TolleranceEndingPoint = 2.0;
            TolleranceStartingAngle = 0.05;
        };

        ASV_angular_position:
	      {
               gain = 0.3;
               confidence = 0.0;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	      };

        ASV_make_curve:
	    {	    
               gain = 1.0;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	    };

        ASV_control_distance:
        {	    
               gain = 0.2;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	    };

};
