task:
{
    ASV_control_velocity_linear:
    {
        gain = 1.0;
        taskEnable = true;
        saturation = 10.0;
    };

    ASV_hold_position:
    {
         gain = 0.3;
         taskEnable = true;
         saturation = 10.0;
         controlReference = [0.0, 0.0, 0.0];
    };
	
    ASV_safety_boundaries:
    {
        gain = 1.0;
        taskEnable = true;
        saturation = 10.0;

        decreasingBellShape:
        {
            xmin = [3.0, 0.0, 0.0];
            xmax = [8.0, 0.0, 0.0];
        };
    };

    PathFollowing:
    {
        MaximumLookupAbscissa = 0.5;
        Delta = 2.0;
        UseLineOfSight = false;
        TolleranceStartingPoint = 2.0;
        TolleranceEndingPoint = 2.0;
        TolleranceStartingAngle = 0.05;
    };

    ASV_angular_position:
    {
         gain = 0.3;
         taskEnable = true;
         saturation = 10.0;
         controlReference = [0.0, 0.0, 0.0];
    };

    ASV_absolute_axis_alignment:
    {
        gain = 0.3;
        taskEnable = true;
        saturation = 10.0;
        controlReference = [0.0, 0.0, 0.0];
    };

    ASV_control_distance:
    {
        gain = 0.1;
        taskEnable = true;
        saturation = 10.0;
        controlReference = [0.0, 0.0, 0.0];
    };
};
