task:
{
        ASV_control_velocity_linear:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
        };

        ASV_control_velocity_angular:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
        };
	
        ASV_horizontal_attitude:
	{	    
                gain = 1.0;
                taskEnable = false;
                saturation = 10.0;
                increasingBellShape:
                {
                    xmin = [ 0.12 ];
                    xmax = [ 0.24  ];
                };
				
	};

        ASV_linear_position_go_to:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
                controlReference = [0.0, 0.0, 0.0];

        };


        ASV_attitude:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
                virtualFrameGain=0.2;
                controlReference = [0.0, 0.0, 0.0];
        };

        ASV_hold_position:
        {
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
                controlReference = [0.0, 0.0, 0.0];
        };
	
        ASV_direction_alignment:
	{	    
                gain = 1.0;
                taskEnable = true;
                saturation = 10.0;
                controlReference = [0.0, 0.0, 0.0];
                axis = [1.0, 0.0, 0.0];
	};


        ASV_safety_boundaries:
        {
                gain = 0.2;
                taskEnable = true;
                saturation = 0.5;
                tollerance = [0.05];
        };

        ASV_angular_position:
	{	    
               gain = 1.0;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	};

        ASV_make_curve:
	{	    
               gain = 0.5;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	};

        ASV_control_distance:
	{	    
               gain = 0.5;
               taskEnable = true;
               saturation = 10.0;
               controlReference = [0.0, 0.0, 0.0];
	};

};
