ulisseModel:
{
    lambdaPos: 13.8;
    lambdaNeg: 10.1;
    motorsTransversalDistance: 0.6925;
    motorsLongitudinalDistance: 1.5;
    #cX: [0.0, 0.0, 40.29];
    #cY: [0.0, 0.0, 80.58];
    #cN: [326.69, 0.0, 272.58];
    #cNneg: [-169.75, 0.0, 841.03];
    #b1Pos: 3.03E-4;
    #b2Pos: 0.0;
    #b1Neg: 1.46E-4;
    #b2Neg: 2.5E-2;

    #cX: [0.0, 0.0, 58.0];
    #cY: [0.0, 0.0, 120.0];
    #cN: [470.0, 0.0, 392.5];
    #cNneg: [-244.5, 0.0, 1211.0];
    #b1Pos: 3.03E-4;
    #b2Pos: 0.0;
    #b1Neg: 1.46E-4;
    #b2Neg: 3.0E-2;

    cX: [0.0, 0.0, 65.0];
    cY: [0.0, 0.0, 300.0];
    cN: [477.0, 0.0, 0.0];
    cNneg: [0.0, 0.0, 1377.0];
    b1Pos: 3.03E-4;
    b2Pos: 0.0;
    b1Neg: 1.37E-4;
    b2Neg: 0.0;
    kPos: 0.069;
    kNeg: 0.31;
    rpmDynState: 0.9718;
    rpmDynPosPerc: 0.3887;
    rpmDynNegPerc: 0.2845;

    inertia: [400.0, 400.0, 300.0];
    hullWidth: 0.4;
};
