ulisseModel:
{
    lambdaPos: 13.0;
    lambdaNeg: 9.1;
    motorsDistance: 0.6925;
    cX: [0.0, 0.0, 58.0];
    cY: [0.0, 0.0, 120.0];
    cN: [470.0, 0.0, 392.5];
    cNneg: [-244.5, 0.0, 1211.0];
    b1Pos: 3.03E-4;
    b2Pos: 0.0;
    b1Neg: 1.46E-4;
    b2Neg: 3.0E-2;
    inertia: [400.0, 400.0, 400.0];
    hullWidth: 0.4;
};
