ulisseModel:
{
    lambdaPos: 13.8;
    lambdaNeg: 10.1;
    motorsTransversalDistance: 0.6925;
    motorsLongitudinalDistance: 1.5;
    #cX: [0.0, 0.0, 40.29];
    #cY: [0.0, 0.0, 80.58];
    #cN: [326.69, 0.0, 272.58];
    #cNneg: [-169.75, 0.0, 841.03];
    #b1Pos: 3.03E-4;
    #b2Pos: 0.0;
    #b1Neg: 1.46E-4;
    #b2Neg: 2.5E-2;

    #cX: [0.0, 0.0, 58.0];
    #cY: [0.0, 0.0, 240.0];
    #cN: [470.0, 0.0, 392.5];
    #cNneg: [-244.5, 0.0, 1211.0];
    #b1Pos: 3.03E-4;
    #b2Pos: 0.0;
    #b1Neg: 1.46E-4;
    #b2Neg: 3.0E-2;

    cX: [0.0, 0.0, 65.0];
    cY: [0.0, 0.0, 1680.0];
    cN: [477.0, 0.0, 0.0];
    cNneg: [0.0, 0.0, 1377.0];
    b1Pos: 3.03E-4;
    b2Pos: 0.0;
    b1Neg: 1.37E-4;
    b2Neg: 0.0;
    kPos: 0.069;
    kNeg: 0.31;
    rpmDynState: 0.9718;
    rpmDynPosPerc: 0.3887;
    rpmDynNegPerc: 0.2845;
    #alfa: 1

    Xup: -2;
    Yvp: -10;
    Yrp: 0;
    Nvp: 0;
    Nrp: -1;
    Xu: -0.7225;
    Yv: -0.8612;
    Yr: -7.25;
    Nv: -0.0313;
    Nr: -1.9;
    Xuu: -1.3274;
    Yvv: -36.2832;
    Yrv: -0.805
    Yvr: -1.33
    Yrr: -3.45;
    Nvv: -3.96;
    Nrv: 0.13;
    Nvr: 0.08;
    Nrr: 0.75;

    m: 400;
    Iz: 300;
    
    inertia: [400.0, 400.0, 300.0];
    hullWidth: 0.4;
};
