sim:
{    
        sim_params:
	{
            dt: 0.001;
	};
        thruster_mapping:
	{
            lambda_pos: 13.0;
            lambda_neg: 9.1;
            motors_distance: 0.6925;
            cX: [0.0, 0.0, 45.47];
            cN: [520.0, 0.0, 600.0];
            b1_pos: 0.000303;
            b2_pos: 0.034;
            b1_neg: 0.00014;
            b2_neg: 0.055;
            Inertia: [400.0, 400.0, 50.0];
	};
};
