rate: 100;

bodyF_gps_sensor_position: [-0.750, 0.0, -1.635];  # x, y, z

#bodyF_dvl_sensor_pose: [1.0, 0.1, 1.0, 0.2, 0.2, -0.2]; # x, y, z, r, p, y
#bodyF_imu_sensor_pose: [1.0, 0.7, 0.0, 0.2, 0.2, 0.2]; # x, y, z, r, p, y
#bodyF_fog_sensor_pose: [1.1, 0.1, 1.1, -0.2, -0.2, 0.2]; # x, y, z, r, p, y

bodyF_dvl_sensor_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]; # x, y, z, r, p, y
bodyF_imu_sensor_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]; # x, y, z, r, p, y
bodyF_fog_sensor_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]; # x, y, z, r, p, y

inertialF_waterCurrent: [0.0, 0.0]; #[m/s]

modelErrorPercentage: 0.0;         # % error

ulisseModel:
{
    inertia: [400.0, 400.0, 300.0];
    hullWidth: 0.4;

    lambdaPos: 13.8;
    lambdaNeg: 10.1;
    motorsTransversalDistance: 0.6925;
    motorsLongitudinalDistance: 1.5;

    rpmDynState: 0.9718;
    rpmDynPosPerc: 0.3887;
    rpmDynNegPerc: 0.2845;
    
    # 4-Quadrant model parameters
    b1_pp: 3.03E-4;
    b2_pp: 7.2E-2;
    b1_pn: 1.6E-4;
    b2_pn: 0.0;
    b1_np: 1.6E-4;
    b2_np: 0.0;
    b1_nn: 1.4E-4;
    b2_nn: 9E-2;
    
    # 2-Quadrant model parameters
    b1Pos: 3.03E-4;
    b2Pos: 0.0;
    b1Neg: 1.37E-4;
    b2Neg: 0.0;

    ######################
    
    ### MODEL M2

    cX: [0.0, 0.0, 65.0];
    cY: [0.0, 0.0, 1680.0];
    cN: [477.0, 0.0, 0.0];
    cNneg: [0.0, 0.0, 1377.0];
    kPos: 0.069;
    kNeg: 0.31;


    ### MODEL BASELINE

    #cX: [0.0, 0.0, 17.0];
    #cY: [0.0, 0.0, 1680.0];
    #cN: [80.0, 0.0, -1.0E-3];
};


sensorsNoise:
{
#    gps_stdd: [0.0, 0.0, 0.0]; #[m]
#
#    gyro_stdd: [0.0, 0.0, 0.0]; #[rad/s]
#
#    gyro_bias:{
#            # b = C + A * sin(2 * PI * f * t)
#            bx:{
#                  C: 0.0;  #[rad/s]
#                  A: 0.0; #[rad/s]
#                  f: 0.0; #[hz]
#                };
#
#            by:{
#                  C: 0.0;  #[rad/s]
#                  A: 0.0; #[rad/s]
#                  f: 0.0; #[hz]
#                };
#
#            bz:{
#                  C: 0.0;  #[rad/s]
#                  A: 0.0; #[rad/s]
#                  f: 0.0; #[hz]
#                };
#            };
#
#    magnetometer_stdd: [0.0, 0.0, 0.0 ];   #[T]
#    compass_stdd: [0.0, 0.0, 0.0 ];        #[rad]
#    accelerometer_stdd: [ 0.0, 0.0, 0.0 ]; #[m/s^2]
#    dvl_stdd: [ 0.0, 0.0, 0.0 ];
#    imu_orientus_stdd: [ 0.0, 0.0, 0.0 ];
#    fog_stdd: 0.0;

    gps_stdd: [0.0, 0.0, 0.0]; #[m]

    gyro_stdd: [0.017448782, 0.017448782, 0.017448782]; #[rad/s]

    gyro_bias:{
            # b = C + A * sin(2 * PI * f * t)
            bx:{
                  C: 0.08;  #[rad/s]
                  A: 0.001; #[rad/s]
                  f: 0.001; #[hz]
                };

            by:{
                  C: 0.08;  #[rad/s]
                  A: 0.001; #[rad/s]
                  f: 0.001; #[hz]
                };

            bz:{
                  C: 0.08;  #[rad/s]
                  A: 0.001; #[rad/s]
                  f: 0.001; #[hz]
                };
            };

    magnetometer_stdd: [0.1E-6, 0.1E-6, 0.1E-6]; #[T]
    compass_stdd: [0.017453501, 0.017453501, 0.011038433]; #[rad]
    accelerometer_stdd: [ 0.0980663043, 0.0980663043, 0.0980663043]; #[m/s^2]
    dvl_stdd: [ 1.0E-6, 1.0E-6, 1.0E-6 ];
    imu_orientus_stdd: [ 1.0E-6, 1.0E-6, 1.0E-6 ];
    fog_stdd: 1.0E-6;
};

wavesSimulator:{
        # b = C + A * sin(2 * PI * f * t)
        wx:{
              C: 0.0;  #[rad/s]
              A: 0.0; #[rad/s]
              f: 1.0; #[hz]
            };

        wy:{
              C: 0.0;  #[rad/s]
              A: 0.0; #[rad/s]
              f: 1.0; #[hz]
            };
};

