
# dimensions for bb creation
max_x_bow: 2.0;
max_x_stern: 1.6;

max_y_starboard: 1.6;
max_y_port: 1.6;

safety_x_bow: 1.5;
safety_x_stern: 1.3;

safety_y_starboard: 1.1;
safety_y_port: 1.1;

gap: 10;



