set(_AMENT_PACKAGE_NAME "ulisse_map")
set(ulisse_map_VERSION "0.0.1")
set(ulisse_map_MAINTAINER "Francesco Wanderlingh <nope@notgoogle.com>")
set(ulisse_map_BUILD_DEPENDS "rclcpp" "std_msgs" "ulisse_msgs" "ulisse_ctrl" "nav_filter" "qtbase5-dev" "qt5-qmake")
set(ulisse_map_BUILDTOOL_DEPENDS "ament_cmake")
set(ulisse_map_BUILD_EXPORT_DEPENDS )
set(ulisse_map_BUILDTOOL_EXPORT_DEPENDS )
set(ulisse_map_EXEC_DEPENDS "libqt5-core" "rclcpp" "std_msgs" "ulisse_msgs" "ulisse_ctrl")
set(ulisse_map_TEST_DEPENDS )
set(ulisse_map_GROUP_DEPENDS )
set(ulisse_map_MEMBER_OF_GROUPS )
set(ulisse_map_DEPRECATED "")
set(ulisse_map_EXPORT_TAGS)
list(APPEND ulisse_map_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
