driver_node:
    ros__parameters:
        DebugBytes: false
        DebugIncomingValidMessageType: false
        DebugFailedCrc: true
	
        LowLevelConfig:
            HbCompass0: 0             # count
            HbCompassMax: 20          # count
            HbMagnetometer0: 10       # count
            HbMagnetometerMax: 30     # count
            HbPacketSensors0: 0       # count
            HbPacketSensorsMax: 20    # count
            HbPacketStatus0: 5        # count
            HbPacketStatusMax: 205    # count
            HbPacketMotors0: 7        # count
            HbPacketMotorsMax: 27     # count
            HbPacketBattery0: 110     # count
            HbPacketBatteryMax: 310   # count
            TimeoutAccelerometer: 2.5 # ms
            TimeoutCompass: 2.5       # ms
            TimeoutMagnetometer: 2.5  # ms
            PwmUpMin: 0.7             # ms
            PwmUpMax: 2.5             # ms
            PwmPeriodMin: 10.0        # ms
            PwmPeriodMax: 30.0        # ms
            PwmTimeThreshold: 1000.0  # ms
            PwmZeroThreshold: 0.05    # s
            DeadzoneTime: 0.025       # s
            ThrusterSaturation: 1000  # %

        ENETHelper:
            MainLoopPeriod: 500       # ms
            CommThreadsPeriod: 500    # ms
            ListeningPort: 12121
            MaxClients: 10
            MaxChannels: 1
            IncomingBandwidth: 0      # 0 means unlimited
            OutgoingBandwidth: 0      # 0 means unlimited

            DefaultValues:
                ahrs:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesSensors:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesStatus:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesConfig:
                   Send: true
                   OnChangeOnly: true
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesAck:
                   Send: true
                   OnChangeOnly: true
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesVersion:
                   Send: true
                   OnChangeOnly: true
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesMotors:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesBatteries:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                eesSw485:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                om2Configuration:
                   Send: true
                   OnChangeOnly: true
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                om2State:
                   Send: true
                   OnChangeOnly: false
                   Period: 1 #in CommThreadsPeriod multiple (periodTime: Period * CommThreadsPeriod)

                ortosDebugConsole:
                   Send: true
