driver_node:
    ros__parameters:
        SerialDevice: "/dev/ttyS0"
        BaudRate: 115200
        EESHelper:
            DebugBytes: false
            DebugIncomingValidMessageType: false
            DebugFailedCrc: true

thread_receiver:
    ros__parameters:
        SerialDevice: "/dev/ttyS0"
        BaudRate: 115200
        EESHelper:
            DebugBytes: false
            DebugIncomingValidMessageType: false
            DebugFailedCrc: true

thread_sender:
    ros__parameters:
        SerialDevice: "/dev/ttyS0"
        BaudRate: 115200
        EESHelper:
            DebugBytes: false
            DebugIncomingValidMessageType: false
            DebugFailedCrc: true
