GPS = {
    SerialDevice = "/dev/ttyS1"
    BaudRate = 115200
}

LLC = {
    BaudRate = 115200
    SerialDevice = "/dev/ttyS0"
    DebugBytes = false;
    DebugIncomingValidMessageType = false;
    DebugFailedCrc = true;

    Config = {
        HbCompass0 = 1000             # count
        HbCompassMax = 20          # count
        HbMagnetometer0 = 10       # count
        HbMagnetometerMax = 30     # count
        HbPacketSensors0 = 0       # count
        HbPacketSensorsMax = 20    # count
        HbPacketStatus0 = 5        # count
        HbPacketStatusMax = 205    # count
        HbPacketMotors0 = 7        # count
        HbPacketMotorsMax = 27     # count
        HbPacketBattery0 = 110     # count
        HbPacketBatteryMax = 310   # count
        TimeoutAccelerometer = 2.5 # ms
        TimeoutCompass = 2.5       # ms
        TimeoutMagnetometer = 2.5  # ms
        PwmUpMin = 0.7             # ms
        PwmUpMax = 2.5             # ms
        PwmPeriodMin = 10.0        # ms
        PwmPeriodMax = 30.0        # ms
        PwmTimeThreshold = 1000.0  # ms
        PwmZeroThreshold = 0.05    # s
        DeadzoneTime = 0.025       # s
        ThrusterSaturation = 1000  # %
    }
}

