Time stamp # (Two-integer timestamp that is expressed as seconds and nanoseconds)
RPY orientation
# RPY orientation_stdd
float64[3] linear_velocity      # [m/s]
float64[3] angular_velocity     # [rad/s]
float64[3] linear_acceleration  # [m/s^2]
float64[3] angular_acceleration # [rad/s^2]
float64[3] accelerometer        # [m/s^2]
float64[3] gyro                 # [rad/s]
float64[2] gyro4x               # [rad/s]
float64[3] magnetometer         # [mG]
float64 temperature             # [°C]

