uint32 timestamp_485
uint8 flags0
uint8 flags1
uint8 master_state
uint8 master_error_code
uint16 motor_voltage    # [1/100 V]
int16 motor_current
uint16 motor_power
int16 motor_speed       # [RPM]
uint8 motor_pcb_temp    # [° celsius]
uint8 motor_stator_temp # [° celsius]
uint8 battery_charge
uint16 battery_voltage  # [1/100 V]
uint16 battery_current  # [1/10 A]
uint16 gps_speed
uint16 range_miles
uint16 range_minutes
uint8 temperature_sw    # sembra fissa a 0
uint8 temperature_rp    # [° celsius]
